apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice
  template:
    metadata:
      labels:
        app: practice
    spec:
      containers:
        - name: practice
          image: niloyrudra/practice
          env:
            - name: PRACTICE_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: PRACTICE_MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: practice-srv
spec:
  selector:
    app: practice
  ports:
    - name: practice
      protocol: TCP
      port: 4002
      targetPort: 4002